###
POST http://localhost:8000/api/tareas HTTP/1.1
Content-Type: application/json

{
    "id": "2",
    "tarea": "Subir a netifly actividad del profesor del modulo 3 - diplomado",
    "fecha": "2023-07-12 14:14",
    "etiqueta": "soporte"
}

###
GET http://localhost:8000/ HTTP/1.1

###
GET http://localhost:8000/api/tareas HTTP/1.1

###
GET http://localhost:8000/api/tareas/64aefba125625a30ace74ea7 HTTP/1.1

###
PUT http://localhost:8000/api/tareas/64aefdf693a825048be5a837 HTTP/1.1
Content-Type: application/json

{
    "id": "3",
    "tarea": "Subir a netifly actividad del profesor del modulo 3 - diplomado",
    "fecha": "2023-07-12 14:16",
    "etiqueta": "desarrollo"
}

###
DELETE http://localhost:8000/api/tareas/64aefba125625a30ace74ea7 HTTP/1.1
